-- Create schemas
CREATE SCHEMA sql_hr;

-- Create UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create tables
CREATE TABLE IF NOT EXISTS sql_hr.employee
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT employee_pk PRIMARY KEY,
    employee_id UUID DEFAULT uuid_generate_v1(),
    first_name  VARCHAR(255),
    last_name   VARCHAR(255),
    job_title   VARCHAR(255),
    salary      DECIMAL(8, 2),
    reports_to  UUID,
    office_id   INT
);

CREATE TABLE IF NOT EXISTS sql_hr.office
(
    id         INT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT office_pk PRIMARY KEY,
    office_id  UUID DEFAULT uuid_generate_v1(),
    code       VARCHAR(10),
    address_id INT
);

CREATE TABLE IF NOT EXISTS sql_hr.address
(
    id         INT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT address_pk PRIMARY KEY,
    address_id UUID DEFAULT uuid_generate_v1(),
    address    VARCHAR(255),
    city       VARCHAR(255),
    state      VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS sql_hr.log
(
    id         INT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT log_pk PRIMARY KEY,
    log_id     UUID DEFAULT uuid_generate_v1(),
    table_name VARCHAR(255),
    operation  VARCHAR(255),
    username   VARCHAR(255),
    date_time  TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sql_hr.responsibility
(
    id                INT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT responsibility_id PRIMARY KEY,
    responsibility_id UUID DEFAULT uuid_generate_v1(),
    name              VARCHAR(50),
    description       VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS sql_hr.rel_employee_responsibility
(
    employee_id       BIGINT NOT NULL
        CONSTRAINT rel_emp_res_pk PRIMARY KEY
        CONSTRAINT fk_rel_emp_with_emp REFERENCES sql_hr.employee (id),

    responsibility_id INT
        CONSTRAINT fk_rel_emp_with_rel REFERENCES sql_hr.responsibility(id)
);

-- Add foreign keys
ALTER TABLE sql_hr.employee
    ADD CONSTRAINT fk_employee_office
        FOREIGN KEY (office_id)
            REFERENCES sql_hr.office (id)
            ON UPDATE CASCADE
            ON DELETE NO ACTION;

ALTER TABLE sql_hr.office
    ADD CONSTRAINT fk_office_address
        FOREIGN KEY (address_id)
            REFERENCES sql_hr.address (id)
            ON UPDATE CASCADE
            ON DELETE NO ACTION;


-- Alter table column
ALTER TABLE sql_hr.employee
    ALTER COLUMN first_name TYPE VARCHAR(100);

-- Drop column
ALTER TABLE sql_hr.employee
    DROP COLUMN last_name;

-- Rename column
ALTER TABLE sql_hr.employee
    RENAME COLUMN first_name TO full_name;

-- Add constraint
ALTER TABLE sql_hr.employee
    ALTER COLUMN full_name SET NOT NULL,
    ALTER COLUMN job_title SET DEFAULT 'Default job title',
    ALTER COLUMN salary SET DEFAULT 1000;

-- Drop constraint
ALTER TABLE sql_hr.employee
    ALTER COLUMN salary DROP DEFAULT;


-- Drop schema
DROP SCHEMA sql_hr CASCADE;

-- Drop table
DROP TABLE sql_hr.rel_employee_responsibility;
